# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/proto/api_yoomoney_server/api_yoomoney_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;service/proto/api_yoomoney_server/api_yoomoney_server.proto\x12\x14\x61pi_yoomoney_service\"\x19\n\x08\x43heckReq\x12\r\n\x05Label\x18\x01 \x01(\t\"\x17\n\tCheckResp\x12\n\n\x02Ok\x18\x01 \x01(\x08\"\'\n\tGetURLReq\x12\r\n\x05Label\x18\x01 \x01(\t\x12\x0b\n\x03Sum\x18\x02 \x01(\x03\"\x19\n\nGetURLResp\x12\x0b\n\x03URL\x18\x01 \x01(\t2\xab\x01\n\x0ePaymentService\x12J\n\x05\x43heck\x12\x1e.api_yoomoney_service.CheckReq\x1a\x1f.api_yoomoney_service.CheckResp\"\x00\x12M\n\x06GetURL\x12\x1f.api_yoomoney_service.GetURLReq\x1a .api_yoomoney_service.GetURLResp\"\x00\x42\x04Z\x02./b\x06proto3')



_CHECKREQ = DESCRIPTOR.message_types_by_name['CheckReq']
_CHECKRESP = DESCRIPTOR.message_types_by_name['CheckResp']
_GETURLREQ = DESCRIPTOR.message_types_by_name['GetURLReq']
_GETURLRESP = DESCRIPTOR.message_types_by_name['GetURLResp']
CheckReq = _reflection.GeneratedProtocolMessageType('CheckReq', (_message.Message,), {
  'DESCRIPTOR' : _CHECKREQ,
  '__module__' : 'service.proto.api_yoomoney_server.api_yoomoney_server_pb2'
  # @@protoc_insertion_point(class_scope:api_yoomoney_service.CheckReq)
  })
_sym_db.RegisterMessage(CheckReq)

CheckResp = _reflection.GeneratedProtocolMessageType('CheckResp', (_message.Message,), {
  'DESCRIPTOR' : _CHECKRESP,
  '__module__' : 'service.proto.api_yoomoney_server.api_yoomoney_server_pb2'
  # @@protoc_insertion_point(class_scope:api_yoomoney_service.CheckResp)
  })
_sym_db.RegisterMessage(CheckResp)

GetURLReq = _reflection.GeneratedProtocolMessageType('GetURLReq', (_message.Message,), {
  'DESCRIPTOR' : _GETURLREQ,
  '__module__' : 'service.proto.api_yoomoney_server.api_yoomoney_server_pb2'
  # @@protoc_insertion_point(class_scope:api_yoomoney_service.GetURLReq)
  })
_sym_db.RegisterMessage(GetURLReq)

GetURLResp = _reflection.GeneratedProtocolMessageType('GetURLResp', (_message.Message,), {
  'DESCRIPTOR' : _GETURLRESP,
  '__module__' : 'service.proto.api_yoomoney_server.api_yoomoney_server_pb2'
  # @@protoc_insertion_point(class_scope:api_yoomoney_service.GetURLResp)
  })
_sym_db.RegisterMessage(GetURLResp)

_PAYMENTSERVICE = DESCRIPTOR.services_by_name['PaymentService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _CHECKREQ._serialized_start=85
  _CHECKREQ._serialized_end=110
  _CHECKRESP._serialized_start=112
  _CHECKRESP._serialized_end=135
  _GETURLREQ._serialized_start=137
  _GETURLREQ._serialized_end=176
  _GETURLRESP._serialized_start=178
  _GETURLRESP._serialized_end=203
  _PAYMENTSERVICE._serialized_start=206
  _PAYMENTSERVICE._serialized_end=377
# @@protoc_insertion_point(module_scope)
