# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from service.proto.api_yoomoney_server import api_yoomoney_server_pb2 as service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/api_yoomoney_service.PaymentService/Check',
                request_serializer=service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.CheckReq.SerializeToString,
                response_deserializer=service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.CheckResp.FromString,
                )
        self.GetURL = channel.unary_unary(
                '/api_yoomoney_service.PaymentService/GetURL',
                request_serializer=service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.GetURLReq.SerializeToString,
                response_deserializer=service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.GetURLResp.FromString,
                )


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetURL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.CheckReq.FromString,
                    response_serializer=service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.CheckResp.SerializeToString,
            ),
            'GetURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetURL,
                    request_deserializer=service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.GetURLReq.FromString,
                    response_serializer=service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.GetURLResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api_yoomoney_service.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api_yoomoney_service.PaymentService/Check',
            service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.CheckReq.SerializeToString,
            service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.CheckResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api_yoomoney_service.PaymentService/GetURL',
            service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.GetURLReq.SerializeToString,
            service_dot_proto_dot_api__yoomoney__server_dot_api__yoomoney__server__pb2.GetURLResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
